### ISSUE TITLE
Describe terrace parameters?

### ISSUE THREAD

**Issue by awickert** [umn-earth-surface/LSDTT-Guide#9]
This could be for a later update -- or even for a different README altogether -- but I would suggest that as you walk through the terrace code, that you document (or link to documentation that describes) how it works and how to modify it. Important topics that have been questions before relate to:
* The Q-Q plots
* Unknown failure conditions (global NULL returns)
* Importing pre-filtered DEMs to produce solutions more rapidly

**Comment by spenprase** [comment]
I'm a bit unclear where to start with this or what exactly you're envisioning here. Are you thinking of adding this into these instructions?

**Comment by awickert** [comment]
Yep. But I'm not sure what above is unclear. Maybe to point out the key: "document (or link to documentation that describes) how it works and how to modify it"
